#include "./parasites.hpp"

std::vector<Card> Cards::parasites(void) {
	return {
		{"River Stench",5,8,5,{"- 12 Opp Attack Min 12"},{"Poison 2 Min 3"},"As one of the deadliest Parasites, the River Stench is hard to be avoided. Humans need water, but if the River Stench has taken over a water source, all of the water down stream is basically undrinkable, unless you want to die in the next three days."},
		{"Organ Melter",3,7,3,{"- 2 Opp Life Min 2"},{"Poison 2 Min 3"},"Organ Melters are small red snakes that don't bite, but rather bury themselves into creatures. They will then remain there for a few days, until they have devoured all of the inner organs of their victims."},
		{"Acidic Former",2,4,4,{"- 3 Opp Damage Min 3"},{"Poison 2 Min 3"},"A mass of a green, slimy liquid that crawls across the floor and melts every organic material it comes in contact with. If you see an Acidic Former, run."},
		{"Separating Splitter",4,6,6,{"- 3 Opp Damage Min 3"},{"Poison 2 Min 3"},"A humanoid mass of blue goo that splits itself upon being hit. Separating Splitters always come in group, and as long as there is no fire around to burn them down, a group they will stay."},
		{"Aerial Floater",4,8,3,{"- 3 Opp Power Min 5"},{"Poison 2 Min 3"},"Imagine a floating ball of colorful spores, now imagine that that ball has a diameter of 3 meters and floats in your direction. Aerial Floaters are quick themselves, but their spores take a while to kick in. The best option is to run, as they often come in groups."},
		{"Massive Gasser",5,6,6,{"- 5 Opp Power Min 5"},{"Poison 2 Min 3"},"When you find a hill that looks like it is about to burst, you have most likely found a Massive Gasser. These Parasites devour organic material underground, producing gas that increases the surface of the organic material around it. A vicious cicle ensues, until they are released into the air, where they get carried by the wind to a new place."},
		{"Rapid Overtaker",3,5,5,{"+ 8 Attack"},{"Poison 2 Min 3"},"The Rapid Overtaker starts out as a small bump under your skin, but quickly becomes a tumor-like growth that overtakes your entire body. It produces rigid edges on the skin of its victims, which cut open new flesh, ready to be overtaken."},
		{"Cannibalistic Consumer",2,8,2,{"Backlash: Self Poison 2 Min 3"},{"Poison 2 Min 3"},"The Cannibalistic Consumer is a Parasite that infects living beings and makes them kill and devour other members of its infected species. This can be humans, but also animals and monsters. Although its not smart to kill potential hosts, the parasite is extremely dangerous. If you ever see a small worm that looks weird, smash or burn it."},
		{"Delayed Spreader",2,6,1,{"Damage = Opp Damage"},{"Poison 2 Min 3"},"The Delayed Spreader spreads through droplets from creature to creature. It is very difficult to cut down an epidemic of this Parasite, as it infects its hosts very slowly, until it is too late. At first you think those are just some pimples, until they burst and never close again."},
		{"Bloater",4,8,3,{"Defeat: - 3 Opp Life Min 2"},{"Poison 2 Min 3"},"The Bloater is a former human whose belly is ready to burst. The body's skin is pale and of a greenish-grey color, teeth are falling out and only strips of hair remain on the head. The Bloater itself is an ant-like parasite that devours the intestines of its victims while producing gas and offspring while controlling the hosts body. When the humanoid body is killed it violently explodes, spreading the produced gas and many of the ant-like creatures around."},
		{"Spore King",5,7,6,{"Defeat: Heal 3 Max 9"},{"Poison 2 Min 3"},"The Spore King is a gargantuan mass of colorful spores that moves around the land and overtakes every organic matter it can find. It does not matter whether its a living creature or plant life, everything gets integrated."},
		{"Overgrowth Shroom",3,7,3,{"Heal 1 Max 15"},{"Poison 2 Min 3"},"The Overgrowth Shroom is a gigantic mushroom, whose network overtakes every organic material in its vicinity."},
		{"Vile Infector",3,8,2,{"Poison 2 Min 3"},{"Poison 2 Min 3"},"The Vile Infector turns the bodies of its hosts into spewers of green liquid, which spreads the Parasite onto other creatures. Through this, a vomiting dog on the streets might be the end of you, forever damned to vomit onto your family until you violently die a few weeks later."},
		{"Shapechanger",3,2,7,{"Power = Opp Power"},{"Poison 2 Min 3"},"The Shapechanger is a translucent liquid, which can change itself into anything, mimicking what stands in front of it. Its end goal is to devour what's in front of it, but don't tell that to the narcissists."},
		{"Gigantic Leech",5,7,3,{"Steal 3 Life Min 1"},{"Poison 2 Min 3"},"The Gigantic Leech is what it is. A Gigantic Leech."},
		{"Airborne Integrator",2,6,2,{"Stop Opp Ability"},{"Poison 2 Min 3"},"The Airborne Integrator turns creatures into brainless husks via its airborne spores. Though if the creatures around it are not brainless, the small mound of mold can be easily burned down to dust."},
		{"Plaguebearer",4,7,5,{"Stop Opp Ability"},{"Poison 2 Min 3"},"A Plaguebearer is a sloth-like creature that carries an immense stench with it. Creatures that smell this stench have a high chance of getting decomposed from the gases that the Plaguebearer emits, turning themselves into small ovens of this stench. Plaguebearers love this smell and love to eat those that smell like that."},
		{"Hookvine",4,8,4,{"Stop Opp Bonus"},{"Poison 2 Min 3"},"A plant overtaken by the Hookvine Parasite will overtake nearby plant mass and develop long vines that it can move freely to pull in further plant mass. Alternatively, a fresh creature can also be pulled in, though that will only be used to squish the liquid juices out of its body to feed the plant."},
		{"Pandemic Oven",3,7,3,{"Stop Opp Bonus"},{"Poison 2 Min 3"},"Feeling like the flu at first, the Pandemic Oven heats up infected creatures, making them seek out water to cool themselves down. Inside of the water, the Pandemic Oven then release its small children through the skin of its victim, which then search for other hosts to heat up."},
		{"Contagious Virus",3,4,5,{"Team: - 4 Opp Attack Min 12"},{"Poison 2 Min 3"},"The Contagious Virus is less of a Parasite and more of a disease. Airborne by nature, it makes creatures act irrationally, often leading them towards other Parasites."},
		{"Shapeworm",4,8,3,{"Team: + 1 Life"},{"Poison 2 Min 3"},"The Shapeworm is one of the weirdest Parasites. Originally a rather large black and red worm with a horn, the Shapeworm slips into corpses and changes their bodies to do its bidding. Hereby, its bidding is mostly producing more corpses to lay eggs or inhabit."},
		{"Combining Mass",3,5,4,{"Team: + 1 Power"},{"Poison 2 Min 3"},"The Combining Mass is one of the most unusual Parasites. It is basicially invisible and magically pulls organic matter together to form a body. Corpses and other meat are preferred by the Parasite, while a living creature is only waiting to be integrated."},
	};
}
