#include "./random.hpp"

std::vector<Card> Cards::random(void) {
	return {
		//{"Living Gargoyle",		4,5,8,{"- 1 Opp Damage Min 3"},	{"+ 2 Power"},"A gargoyle made of stone that is alive."},
		//{"Basilisk",			3,7,4,{"- 1 Opp Power Min 4"},	{"+ 2 Power"},"A basilisk."},
		//{"Mountain Troll",		5,7,8,{"- 2 Opp Damage Min 5"},	{"+ 2 Power"},"An ape-like creature covered in heavy fur with stone-like skin."},
		//{"Beast of the Fields",	5,8,6,{"- 8 Opp Attack Min 10"},{"+ 2 Power"},"An ape-like creature with a wolf's head and a bone-blade arm. Extremely dangerous and deadly."},
		//{"Rabies Bison",		2,6,3,{"+ 1 Damage"},			{"+ 2 Power"},"A bison with rabies. It is volatile and angry."},
		//{"Red Dragon",			5,8,6,{"+ 2 Damage"},			{"+ 2 Power"},"A red dragon that spews mountains of fire at its victims."},
		//{"Burrower",			3,6,4,{"+ 2 Power"},			{"+ 2 Power"},"A mole like creature with blade-like claws and a sturdy armor like an armadillo."},
		//{"Monster8",			3,8,3,{"+ 4 Attack"},			{"+ 2 Power"},"A snake like creature with small legs that moves very fast."},

		// aberrations selection
		//{"Bone Monger",3,5,5,{"- 2 Opp Damage Min 1"},{"Stop Opp Bonus"},"A humanoid fleshy creature with the bones of its victims attached to its body. Teeth spike from all parts of its body."},
		//{"Cloaker",3,5,5,{"- 2 Opp Power Min 4"},{"Stop Opp Bonus"},"An invisible flying creature that is rarely seen, though it sparkles in light. It looks similar to a devilfish."},
		//{"Ripper",2,6,1,{"- 3 Opp Damage Min 2"},{"Stop Opp Bonus"},"A humanoid creature that strips its body of its flesh to attack anything suitable for consumption. Its own flesh is stripped of similar to what it does to its victims"},
		//{"Eye Wolf",3,5,3,{"- 4 Opp Power Min 4"},{"Stop Opp Bonus"},"A wolf-like creature with green eyes covering its entire body."},
		//{"Devourer",3,6,3,{"+ 1 Life per Damage"},{"Stop Opp Bonus"},"A mass of fleshy mouths with different kind of teeth all over its body."},
		//{"Splitter",3,7,3,{"+ 2 Power"},{"Stop Opp Bonus"},"A large mouth sits on a blueish hairy humanoid body with 2 arms that splits into 4 arms."},
		//{"Gobbler",2,6,1,{"+ 3 Life"},{"Stop Opp Bonus"},"A small baby-like creature with an insanely large mouth."},
		//{"Slitherer",3,7,3,{"+ 8 Attack"},{"Stop Opp Bonus"},"A snake-like creature that splits up into a mass of snakes."},
		//{"Shellshocker",4,5,7,{"Courage: - 3 Opp Power Min 4"},{"Stop Opp Bonus"},"A huge, grey crab-like creature with lightning arcing between parts of its bodies."},
		//{"Doppelganger",4,7,7,{"Damage = Opp Damage"},{"Stop Opp Bonus"},"A greyish blue humanoid creature that can change its body at will into other creatures, creating a perfect copy in the process."},
		//{"Tendril Bearer",5,7,6,{"Defeat: - 3 Opp Life Min 2"},{"Stop Opp Bonus"},"A hulking, hairy mass of a beast with fleshy tendrils and tentacles coming out of many parts of its body."},
		//{"Brain Dragon",5,7,7,{"Stop Opp Ability"},{"Stop Opp Bonus"},"A dragon with a gigantic brain mounted on its back that slithers to the wings and its head."},
		//{"Evil Eye",4,6,6,{"Stop Opp Ability"},{"Stop Opp Bonus"},"A flying eye with immense pressure it opposes on creatures around it."},

		// clerics selection
		//{"Mass Servant",2,5,3,{"- 2 Opp Damage Min 1"},{"Stop Opp Ability"},"The Mass Serant is dressed in simple robes and always there to accomodate the priests and Clerics."},
		//{"Hollow Cleric",4,7,3,{"- 4 Opp Life Min 2"},{"Stop Opp Ability"},"The Hollow Cleric is ready to fill the emptyness in your heart. His robes are of a dark blue color and reflect the sunlight."},
		//{"Prophet",4,8,2,{"- 4 Opp Potion Min 2"},{"Stop Opp Ability"},"The Prophet is one of a kind, foretold by the scriptures. He is as charismatic as he is strong and he wears the finest Cleric clothes."},
		//{"Peace Cleric",4,7,3,{"- 5 Opp Damage Min 2"},{"Stop Opp Ability"},"The Piece Cleric is keeping peace among all. He wears simple brown robes and is very old."},
		//{"Tempest Cleric",3,8,2,{"- 8 Opp Attack Min 3"},{"Stop Opp Ability"},"The Tempest Cleric's robes are of grey color and very light, almost floaty."},
		//{"Water Cleric",4,5,6,{"+ 12 Attack"},{"Stop Opp Ability"},"The Water Cleric wears bright blue robes and is mostly found blessing barrels and fountains of water."},
		//{"Life Cleric",5,6,2,{"+ 3 Life per Damage"},{"Stop Opp Ability"},"The Life Cleric wears golden robes and heals everyone, poor or rings."},
		//{"Nature Cleric",3,7,2,{"+ 3 Potion"},{"Stop Opp Ability"},"The Nature Cleric has green robes and knows how to tend plants."},
		//{"War Cleric",4,7,5,{"Courage: + 3 Power"},{"Stop Opp Ability"},"The War Cleric wears heavy metal armor underneath his robes and carries a battleaxe and shield."},
		//{"Oracle",4,5,5,{"Defeat: - 3 Opp Life Min 0"},{"Stop Opp Ability"},"The Oracle wears ragged clothing and is mostly found in its room with different smells and scents."},
		//{"Nightmare Cleric",3,4,6,{"Revenge: + 3 Power"},{"Stop Opp Ability"},"The Nightmare Cleric helps people with their nightmares and is wrapped in bright white robes with dark dots."},
		//{"Vengeance Cleric",5,7,5,{"Revenge: + 5 Damage"},{"Stop Opp Ability"},"The Vengeance Cleric has a small piece of paper with him at all times. His robes are of red color."},
		//{"Pastor",3,6,4,{"Stop Opp Bonus"},{"Stop Opp Ability"},"The Pastor prays to the gods and has information from the many people that talk to him."},
		//{"Stability Cleric",4,7,5,{"Stop Opp Bonus"},{"Stop Opp Ability"},"The Stability Cleric keeps things as they are and is mostly carrying around scriptures and books. His robes are of silver color."},
		//{"Inquisitor",3,7,1,{"Stop: + 6 Damage"},{"Stop Opp Ability"},"The Inquisitor is there to charge those that do wrong. He wears heavy brown robes and metal armor underneath."},
		//{"Acolyte",3,7,3,{"Heal 1 Max 15"},{"Stop Opp Ability"},"The Acolyte is there to help in the masses and help the Clerics with things."},
		//{"Preacher",2,6,2,{"Heal 2 Max 10"},{"Stop Opp Ability"},"The Preacher stands out on the marketplace and ushers citizens to the temples of the Clerics."},
		//{"Death Cleric",5,8,1,{"Poison 3 Min 0"},{"Stop Opp Ability"},"The Death Cleric wears dark green robes and carries an orb with him."},


		// bandits
		//{"Deminisher",3,4,6,{"- 2 Opp Potion Min 5"},{"Team: + 3 Attack"},"Always look after your stash, or the Deminisher might just half it. Small and nimble, he takes everything he can get his hands on, though he is only there for a quick bite of your stuff. You might mistake him for a child, as he is rather small, but don't let his size fool you, as he is well equipped with daggers and lockpicks"},
		//{"Rogue Veteran",4,6,6,{"- 2 Opp Power Min 6"},{"Team: + 3 Attack"},"Knowing the guard rotation in and out and having served in an army, the Rogue Veteran uses his knowledge to always be a step ahead. Heavy metal armor and his trusty crossbow are as important as knowing where to go and where to shoot."},
		//{"Watcher",3,5,4,{"- 3 Opp Damage Min 3"},{"Team: + 3 Attack"},"The Watcher is there to overlook the area of the camp and is camouflaged with sticks and leaves integrated into his leather armor. In case of a battle he only has a small dagger, but that is usually enough."},
		//{"Former Trader",4,7,3,{"+ 3 Potion"},{"Team: + 3 Attack"},"Posing as a merchant, the Former Trader not only still has a small wagon with all kinds of goods he sells, but also his formal merchant clothing at his disposal. A part of his income is still earned legitimately, though those that buy off him often get robbed."},
		//{"Rusher",3,6,6,{"Backlash: - 3 Potion Min 0"},{"Team: + 3 Attack"},"Always the first to take charge in a raid, the Rusher in his light leather armor is always at the front with his shortsword and buckler. Usually, he is also the first to need a healing potion."},
		//{"Vengeful Impersonator",2,6,2,{"Courage: Stop Opp Bonus"},{"Team: + 3 Attack"},"The Vengeful Impersonator has a talent for appearing as someone else and uses this to infiltrate gatherings of his enemies in order to disrupt them. His outfits range from colorful noble outfits to the dirty rags of a homeless person, depending on what is needed for the job."},
		//{"Stash Burner",5,7,6,{"Damage = Opp Damage"},{"Team: + 3 Attack"},"An arsonist at heart, the Stash Burner can always be found with flint and steel in his hands. Some dry hay is always peeking out of his pockets and he carries this weird black tar around with him in bottles."},
		//{"Fallback Man",3,7,2,{"Defeat: + 2 Life"},{"Team: + 3 Attack"},"The Fallback Man is there when your first plan doesn't work out as intended. He is always on standby and ready to step in to help you if you fucked up."},
		//{"Former Worker",2,5,3,{"Revenge: + 2 Power"},{"Team: + 3 Attack"},"Kicked from his formed job, the Former Worker was a craftsmen that got fired. As nothing else cuts it, he became a bandit. He still wears his old clothing though, but now it is dirty and most of it is different shades of brown."},
		//{"Last One Standing",4,6,5,{"Revenge: + 3 Damage"},{"Team: + 3 Attack"},"The Last One Standing once belonged to another group of bandits, but was nearly killed when his whole group got killed. He carries the weapons of his brethren and many scars into battle."},
		//{"Hateful Targeter",5,6,8,{"Revenge: Stop Opp Bonus"},{"Team: + 3 Attack"},"More often than not, money is money, but for the Hateful Targeter, there needs to be something personal in the mix before he goes out robbing people. Equipped with a heavy metal mace, he may leave his targets alive, but they will be broken for life, physically and mentally."},
		//{"Trap Layer",3,5,4,{"Stop Opp Ability"},{"Team: + 3 Attack"},"Sometimes mistaken for a hunter, the Trap Layer has all kinds of bear traps, smoke bombs and other equipment on his belt and in his backpack. His clothing is rather uninteresting and what common folk would wear, but a hood is always in the picture."},
		//{"Former Noble",5,6,7,{"Team: - 3 Opp Attack Min 12"},{"Team: + 3 Attack"},"As a former noble, the Former Noble still has some connections that allow him to know where nobles will travel. Even though he now wears a heavy leather armor, he can't let go of his golden rings."},
		//{"Inciter",5,7,5,{"Team: + 1 Damage"},{"Team: + 3 Attack"},"Rarely unable to procure the equipment one needs, the Inciter has a silver tongue, literally. He always knows what to say to get his peers riled up and ready to take some caravans on."},
		//{"Old Captain",4,4,6,{"Team: + 1 Power"},{"Team: + 3 Attack"},"This Old Captain stepped out of retired to get some more money. He kept his heavy armor and his heavy greatsword, but he might need some help putting it on."},
		//{"Camp Cook",3,4,5,{"Team: + 3 Attack"},{"Team: + 3 Attack"},"Out in the forest, the Camp Cook can create a hearty meal from stolen goods. Don't ever get on his bad side, because else the entire camp will hunt you down. He still wears his old white cooks clothing, though they have become a bit dirty over the years."},


		// parasites
		{"River Stench",5,8,5,{"- 12 Opp Attack Min 12"},{"Poison 2 Min 3"},"As one of the deadliest Parasites, the River Stench is hard to be avoided. Humans need water, but if the River Stench has taken over a water source, all of the water down stream is basically undrinkable, unless you want to die in the next three days."},
		{"Organ Melter",3,7,3,{"- 2 Opp Life Min 2"},{"Poison 2 Min 3"},"Organ Melters are small red snakes that don't bite, but rather bury themselves into creatures. They will then remain there for a few days, until they have devoured all of the inner organs of their victims."},
		{"Acidic Former",2,4,4,{"- 3 Opp Damage Min 3"},{"Poison 2 Min 3"},"A mass of a green, slimy liquid that crawls across the floor and melts every organic material it comes in contact with. If you see an Acidic Former, run."},
		{"Separating Splitter",4,6,6,{"- 3 Opp Damage Min 3"},{"Poison 2 Min 3"},"A humanoid mass of blue goo that splits itself upon being hit. Separating Splitters always come in group, and as long as there is no fire around to burn them down, a group they will stay."},
		{"Aerial Floater",4,8,3,{"- 3 Opp Power Min 5"},{"Poison 2 Min 3"},"Imagine a floating ball of colorful spores, now imagine that that ball has a diameter of 3 meters and floats in your direction. Aerial Floaters are quick themselves, but their spores take a while to kick in. The best option is to run, as they often come in groups."},
		{"Massive Gasser",5,6,6,{"- 5 Opp Power Min 5"},{"Poison 2 Min 3"},"When you find a hill that looks like it is about to burst, you have most likely found a Massive Gasser. These Parasites devour organic material underground, producing gas that increases the surface of the organic material around it. A vicious cicle ensues, until they are released into the air, where they get carried by the wind to a new place."},
		{"Rapid Overtaker",3,5,5,{"+ 8 Attack"},{"Poison 2 Min 3"},"The Rapid Overtaker starts out as a small bump under your skin, but quickly becomes a tumor-like growth that overtakes your entire body. It produces rigid edges on the skin of its victims, which cut open new flesh, ready to be overtaken."},
		{"Cannibalistic Consumer",2,8,2,{"Backlash: Self Poison 2 Min 3"},{"Poison 2 Min 3"},"The Cannibalistic Consumer is a Parasite that infects living beings and makes them kill and devour other members of its infected species. This can be humans, but also animals and monsters. Although its not smart to kill potential hosts, the parasite is extremely dangerous. If you ever see a small worm that looks weird, smash or burn it."},
		{"Delayed Spreader",2,6,1,{"Damage = Opp Damage"},{"Poison 2 Min 3"},"The Delayed Spreader spreads through droplets from creature to creature. It is very difficult to cut down an epidemic of this Parasite, as it infects its hosts very slowly, until it is too late. At first you think those are just some pimples, until they burst and never close again."},
		{"Bloater",4,8,3,{"Defeat: - 3 Opp Life Min 2"},{"Poison 2 Min 3"},"The Bloater is a former human whose belly is ready to burst. The body's skin is pale and of a greenish-grey color, teeth are falling out and only strips of hair remain on the head. The Bloater itself is an ant-like parasite that devours the intestines of its victims while producing gas and offspring while controlling the hosts body. When the humanoid body is killed it violently explodes, spreading the produced gas and many of the ant-like creatures around."},
		{"Spore King",5,7,6,{"Defeat: Heal 3 Max 9"},{"Poison 2 Min 3"},"The Spore King is a gargantuan mass of colorful spores that moves around the land and overtakes every organic matter it can find. It does not matter whether its a living creature or plant life, everything gets integrated."},
		{"Overgrowth Shroom",3,7,3,{"Heal 1 Max 15"},{"Poison 2 Min 3"},"The Overgrowth Shroom is a gigantic mushroom, whose network overtakes every organic material in its vicinity."},
		{"Vile Infector",3,8,2,{"Poison 2 Min 3"},{"Poison 2 Min 3"},"The Vile Infector turns the bodies of its hosts into spewers of green liquid, which spreads the Parasite onto other creatures. Through this, a vomiting dog on the streets might be the end of you, forever damned to vomit onto your family until you violently die a few weeks later."},
		{"Shapechanger",3,2,7,{"Power = Opp Power"},{"Poison 2 Min 3"},"The Shapechanger is a translucent liquid, which can change itself into anything, mimicking what stands in front of it. Its end goal is to devour what's in front of it, but don't tell that to the narcissists."},
		{"Gigantic Leech",5,7,3,{"Steal 3 Life Min 1"},{"Poison 2 Min 3"},"The Gigantic Leech is what it is. A Gigantic Leech."},
		{"Airborne Integrator",2,6,2,{"Stop Opp Ability"},{"Poison 2 Min 3"},"The Airborne Integrator turns creatures into brainless husks via its airborne spores. Though if the creatures around it are not brainless, the small mound of mold can be easily burned down to dust."},
		{"Plaguebearer",4,7,5,{"Stop Opp Ability"},{"Poison 2 Min 3"},"A Plaguebearer is a sloth-like creature that carries an immense stench with it. Creatures that smell this stench have a high chance of getting decomposed from the gases that the Plaguebearer emits, turning themselves into small ovens of this stench. Plaguebearers love this smell and love to eat those that smell like that."},
		{"Hookvine",4,8,4,{"Stop Opp Bonus"},{"Poison 2 Min 3"},"A plant overtaken by the Hookvine Parasite will overtake nearby plant mass and develop long vines that it can move freely to pull in further plant mass. Alternatively, a fresh creature can also be pulled in, though that will only be used to squish the liquid juices out of its body to feed the plant."},
		{"Pandemic Oven",3,7,3,{"Stop Opp Bonus"},{"Poison 2 Min 3"},"Feeling like the flu at first, the Pandemic Oven heats up infected creatures, making them seek out water to cool themselves down. Inside of the water, the Pandemic Oven then release its small children through the skin of its victim, which then search for other hosts to heat up."},
		{"Contagious Virus",3,4,5,{"Team: - 4 Opp Attack Min 12"},{"Poison 2 Min 3"},"The Contagious Virus is less of a Parasite and more of a disease. Airborne by nature, it makes creatures act irrationally, often leading them towards other Parasites."},
		{"Shapeworm",4,8,3,{"Team: + 1 Life"},{"Poison 2 Min 3"},"The Shapeworm is one of the weirdest Parasites. Originally a rather large black and red worm with a horn, the Shapeworm slips into corpses and changes their bodies to do its bidding. Hereby, its bidding is mostly producing more corpses to lay eggs or inhabit."},
		{"Combining Mass",3,5,4,{"Team: + 1 Power"},{"Poison 2 Min 3"},"The Combining Mass is one of the most unusual Parasites. It is basicially invisible and magically pulls organic matter together to form a body. Corpses and other meat are preferred by the Parasite, while a living creature is only waiting to be integrated."},
	};
}
